# Generated by Django 3.2.19 on 2023-07-01 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('Tanks', 'Tanks'), ('Heals', 'Heals'), ('DD', 'DD'), ('Traders', 'Traders'), ('Guildmaster', 'Guildmaster'), ('Questgiver', 'Questgiver'), ('Blacksmith', 'Blacksmith'), ('Leatherworker', 'Leatherworker'), ('Potion Master', 'Potion Master'), ('Spellmaster', 'Spellmaster')], max_length=128, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Description')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='advert.advert', verbose_name='Advert')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
