# Generated by Django 3.2.19 on 2023-07-03 05:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
